# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0002_auto_20180206_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.Multimedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimedia Comment',
                'ordering': ('date',),
                'verbose_name_plural': 'Multimedia Comments',
            },
        ),
    ]
