# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 07:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_multimediacomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.AddField(
            model_name='multimedia',
            name='bloc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multimedia.CategorieMedia'),
            preserve_default=False,
        ),
    ]
